spring:
  datasource:
    url: jdbc:mysql://47.105.184.154:3306/hole?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: hole
    password: Hole#password2020
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  #初始化时建立物理连接的个数
    druid:
      initial-size: 1
  #最小连接池数量
      min-idle: 3
  #最大连接池数量
      max-active: 10
  #获取连接时最大等待时间
      max-wait: 60000
  #配置监控页面访问登录名称
      stat-view-servlet.login-username: admin
  #配置监控页面访问密码
      stat-view-servlet.login-password: password
  #是否开启慢sql查询监控
      filter.stat.log-slow-sql: true
  #慢SQL执行时间
      filter.stat.slow-sql-millis: 1